config/routes.rb
Inventory::Application.routes.draw do
  get "users/new"
	resources :users
	resources :sessions, only: [:new, :create, :destroy]
	
	get '/landing_page', to: 'static_pages#landing_page'
	get '/signup', to: 'users#new'
	get '/signin', to: 'sessions#new'
	delete '/signout', to: 'sessions#destroy', via: :delete
	
	resources :supplier_prices do
		collection do
			get :sort
		end
	end
	
	resources :suppliers do
		collection do
			get :autocomplete
		end
		member do
			post :csv
		end
	end
	
	resources :ship_terms do
		collection do
			get :autocomplete
		end
	end
	
	resources :customers do
		member do
			get :send_email
			get :send_oe_email
			get :send_customer_email
			get :new_order
		end
	end
	root to: 'static_pages#home'
	
	resources :products do
	member do
			get :cogs
		end
	collection do
			get :inventory_worksheet
			get :inventory_worksheet_print
			get :autocomplete
			get :monthly
			get :create_csv
			get :accounting_csv
			get :all_cogs
			get :canada_sales
			get :margin
			get :margin_csv
		end
	end
	resources :product_counts
	resources :skus do
		member do
			get :fees
		end
	end
	resources :events do
		collection do
			get :inventory
			get :amz_inventory
			get :po
			get :fba
			get :po_received
			get :new_inventory
			get :new_po
			post :load
			get :new_fba
			post :load_fba_shipment
			get :new_shipping_plan
			post :create_shipping_plan
		end
		member do
			get :receive_po_today
			get :edit_fba
			get :label
		end
	end
	resources :orders do
		member do
			post :replace
		end
		collection do
			get :new_phone
			get :create_phone
			post :create_single
		  post :destroy_range
			get :combo
			get :orphans
			post :load_data
		end
	end
	resources :offerings do
		member do
			patch :replace
		end
		collection do
				get :blank
				get :autocomplete
				get :autocomplete_sku
				get :autocomplete_no_price
				get :all
				post :add_price_csv
				post :add_sku_csv
				get :create_csv
		end
	end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    start_day = Date.today - 1.month
    end_day = Date.today - 1.day
    sql = ActiveRecord::Base.connection()
    d=sql.execute("SELECT orders.count as count, orders.date as dates from orders WHERE orders.date >= '#{start_day}'::date AND orders.date <= '#{end_day}'::date GROUP BY orders.date ORDER BY orders.date")
    cnt=d.map { |a| a["count"].to_i }
    dates=d.map { |a| Date.parse(a["dates"]) }
    dates2=(start_day..end_day).to_a
    cnt2=Array.new(dates2.length,0) 
    dates.each_with_index do |d,i|
      cnt2[dates2.index(d)]=cnt[i]
    end
    @no_orders=cnt2.sum{ |a| a < 1 ? 1 : 0 }
    @empty_offering= Offering.includes(:products).where("products.id IS NULL").references(:products).count
    @late_pos=Event.unreceived.where("expected_date < ?",Date.today).count
 		@title ="RubberBanditz Inventory Launching Page"
 		@subtitle= "What would you like to do?"
  end
  
  def paypal
  	redirect_to "https://www.paypal.com/us/vst/id=#{params[:Order_ID]}"
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/home.html.erb
<% if @no_orders > 0 %>
  <div class="alert alert-error">
      Days with no orders in last month: <%= @no_orders %> <%= link_to "load missing days", new_order_path %>
</div>
<% end %>

<% if @empty_offering > 0 %>
  <div class="alert alert-error">
      Offerings with no products: <%= @empty_offering %> <%= link_to "enter offering data", offerings_path(blank: true) %>
</div>
<% end %>

<% if @late_pos > 0 %>
  <div class="alert alert-error">
      Late Purchase Orders: <%= @late_pos %> <%= link_to "view late orders", po_events_path(event_type: "Late") %>
</div>
<% end %>

<ul class="home">
<li class="top"><%= link_to "Count Inventory", new_inventory_events_path, class: "btn btn-large btn-primary" %></li>
<li class="top"><%= link_to "Inventory Worksheet", inventory_worksheet_products_path, class: "btn btn-large btn-primary" %></li>
<li class="top"><%= link_to "Place an order from suppliers", new_po_events_path, class: "btn btn-large btn-primary"  %></li>
<li class="top"><%= link_to "View All Shipments", po_events_path, class: "btn btn-large btn-primary"  %></li>
<li class="top"><%= link_to "Upload Shipworks CSV", new_order_path, class: "btn btn-large btn-primary"  %></li>

</ul>