config/routes.rb
Inventory::Application.routes.draw do
  get "users/new"
	resources :users
	resources :sessions, only: [:new, :create, :destroy]
	
	get '/landing_page', to: 'static_pages#landing_page'
	get '/signup', to: 'users#new'
	get '/signin', to: 'sessions#new'
	delete '/signout', to: 'sessions#destroy', via: :delete
	
	resources :supplier_prices do
		collection do
			get :sort
		end
	end
	
	resources :suppliers do
		collection do
			get :autocomplete
		end
		member do
			post :csv
		end
	end
	
	resources :ship_terms do
		collection do
			get :autocomplete
		end
	end
	
	resources :customers do
		member do
			get :send_email
			get :send_oe_email
			get :send_customer_email
			get :new_order
		end
	end
	root to: 'static_pages#home'
	
	resources :products do
	member do
			get :cogs
		end
	collection do
			get :inventory_worksheet
			get :inventory_worksheet_print
			get :autocomplete
			get :monthly
			get :create_csv
			get :accounting_csv
			get :all_cogs
			get :canada_sales
			get :margin
			get :margin_csv
		end
	end
	resources :product_counts
	resources :skus do
		member do
			get :fees
		end
	end
	resources :events do
		collection do
			get :inventory
			get :amz_inventory
			get :po
			get :fba
			get :po_received
			get :new_inventory
			get :new_po
			post :load
			get :new_fba
			post :load_fba_shipment
			get :new_shipping_plan
			post :create_shipping_plan
		end
		member do
			get :receive_po_today
			get :edit_fba
			get :label
		end
	end
	resources :orders do
		member do
			post :replace
		end
		collection do
			get :new_phone
			get :create_phone
			post :create_single
		  post :destroy_range
			get :combo
			get :orphans
			post :load_data
		end
	end
	resources :offerings do
		member do
			patch :replace
		end
		collection do
				get :blank
				get :autocomplete
				get :autocomplete_sku
				get :autocomplete_no_price
				get :all
				post :add_price_csv
				post :add_sku_csv
				get :create_csv
		end
	end
end

app/models/offering.rb
class Offering < ActiveRecord::Base
	include ActionView::Helpers::TextHelper
	require 'csv'
  has_many :orders, :foreign_key => "offering_id", :dependent => :destroy
  has_many :offering_products, :foreign_key => "offering_id", :dependent => :destroy
  has_many :products, through: :offering_products
  belongs_to :sku, :class_name => "Sku"
  accepts_nested_attributes_for :offering_products, :reject_if => :all_blank, :allow_destroy => true
  validates :name, presence: true
  scope :with_n_products, lambda {|n| {:joins => :offering_products, :group => "offering_products.offering_id", :having => ["count(offering_id) = ?", n]}}

require 'peddler'
require 'active_support'

  def value
  	sql = ActiveRecord::Base.connection()
  	d=sql.execute("SELECT SUM(products.price * offering_products.quantity) as purchases FROM offerings INNER JOIN offering_products ON offering_products.offering_id = offerings.id INNER JOIN products ON products.id = offering_products.product_id WHERE (offerings.id = #{id})")
  	return d[0]["purchases"].to_f
  end
   
	def sku_name
  	sku.try(:name)
  end
  
  def sku_name=(name)
  	self.sku = Sku.where(name: name).first_or_create if name.present?
  end
 
  def self.search(search,price)
  	if search
			words = search.to_s.strip.split
		  words.inject(all) do |combined_scope, word|
		  	if price
		    	combined_scope.includes(:products).where('products.id NOT NULL AND LOWER(offerings.name) LIKE ? AND price > 0',"%#{word.downcase}%").references(:products)
		    else	
					combined_scope.includes(:products).where('products.id IS NOT NULL AND LOWER(offerings.name) LIKE ?',"%#{word.downcase}%").references(:products)
		    end
		  end
  	else
  		return all
  	end
  end
    
  def self.add_price(file)
  	offs ={}
  	prices={}
  	csv_text = File.read(file)
  	i=0
		CSV.parse(csv_text, headers: true, col_sep: "\t") do |row|
			offs[i]=row[0]
  		prices[i]= row[1]
  		i=i+1
		end
		return prices
  end
  
	def total_weight
		sql = ActiveRecord::Base.connection()
		d=sql.execute("SELECT SUM(products.weight * offering_products.quantity) FROM offerings INNER JOIN offering_products ON offering_products.offering_id = offerings.id INNER JOIN products ON products.id = offering_products.product_id WHERE (offerings.id = #{self.id})")
		return d.map { |a| a["sum"].to_f }[0]
	end
end

app/controllers/offerings_controller.rb
class OfferingsController < ApplicationController
  require 'will_paginate/array'
  require 'active_shipping'
 	require 'csv'
	include ActiveMerchant::Shipping
  def new
  end

  def edit
  	@offering=Offering.find(params[:id])
  	@title = "Edit Offering"
  	@offering.offering_products.build
  	session[:last_page] = request.env['HTTP_REFERER'] || offerings_url
  end
  
  def destroy
		Offering.find(params[:id]).destroy
	  redirect_to offerings_path
  end
  
	def update
		@offering = Offering.find(params[:id])
	  @offering.update_attributes(offering_params)
	  @title = "Current Offerings and their products"
	  respond_to do |format|
			format.html { redirect_to session[:last_page] }
			format.js
		end
	end
	
	def add_price_csv
		infile = params['/offerings'][:file].read
		CSV.parse(infile, headers: true, col_sep: "\t") do |row|
			off=Offering.find_by(name: row["name"])
			if !off.blank?
				off.update_attributes(price: row["price"])
			end
		end
		flash[:success] = "Prices Loaded"
		redirect_to offerings_path
	end
	
	def add_sku_csv
		infile = params['/offerings'][:file].read
		CSV.parse(infile, headers: true, col_sep: "\t") do |row| 
			Offering.find_by(name: row["name"]).update_attributes(sku: row["sku"]) if !Offering.find_by(name: row["name"]).blank?
		end
		flash[:success] = "Skus Loaded"
		redirect_to offerings_path
	end
		  
  def create_csv
		csv = CSV.generate(col_sep: "\t") do |csv|
			csv << ["name", "sku","price","products"]
			Offering.all.sort_by(&:id).each do |offer|
				csv << [offer.name, offer.sku,	offer.price, offer.offering_products.map{ |o| "#{o.quantity} - #{o.product.name}" }.join(', ')]
			end
		end
		file ="offers.txt"
		File.open(file, "w"){ |f| f << csv }
		send_file( file, type: 'text/csv')
	end

	def replace
		@offering = Offering.find(params[:id])
		offering_id=@offering.id
		replace=Offering.find_or_create_by(name: params[:offering][:name])
		replace.save!
		Order.where(offering_id: offering_id).update_all({:offering_id => replace.id})
		if Order.where(offering_id: offering_id).blank?
			@offering.destroy
		end
		@title = "Current Offerings and their products"
		@offerings=Offering.includes(:products).where("products.id IS NULL").references(:products).paginate(:page => params[:page], :per_page => 10)
	  @blank = true
	  respond_to do |format|
			format.html { render :index }
		end
	end
	
	def autocomplete
		@offerings = Offering.search(params[:term],true)
		render json: @offerings.map(&:name)
	end
	
	def autocomplete_sku
		@skus = Sku.search(params[:term])
		render json: @skus.map(&:name).uniq
	end
	
	def autocomplete_no_price
		@offerings = Offering.search(params[:term],false)
		render json: @offerings.map(&:name)
	end
	
	def price
		@offerings = Offering.search(params[:term],true)
		render json: @offerings.map(&:price)
	end
	
	def show
		@offering = Offering.find(params[:id])
		@title = @offering.sku
		package=Package.new(@offering.total_weight, [5,5], :units => :imperial)
		origin = Location.new(:country => 'US',:zip => '27217')
		destination_US = Location.new(:country => 'US',:zip => '90210')
		destination_CA = Location.new( :country => 'CA')
		destination_CN = Location.new( :country => 'CN')
		destination_EU = Location.new( :country => 'GB')
		ups = UPS.new(:login => 'rubberbanditz', :password => 'Bandtastic2013', :key => 'DCBBB7D0DD606DD6')
		usps = USPS.new(:login => '970RUBBE0314')
		@response_ups_CA = ups.find_rates(origin, destination_CA, package)
		@response_usps_CA = usps.find_rates(origin, destination_CA, package)
		@response_ups_CN = ups.find_rates(origin, destination_CN, package)
		@response_usps_CN = usps.find_rates(origin, destination_CN, package)
		@response_ups_EU = ups.find_rates(origin, destination_EU, package)
		@response_usps_EU = usps.find_rates(origin, destination_EU, package)
		@response_ups_US = ups.find_rates(origin, destination_US, package)
		@response_usps_US = usps.find_rates(origin, destination_US, package)
	end
	
  def index
    @title = "Current Offerings and their products"
    @search=params[:search]
  	@offerings = Offering.search(@search,false)
  	@blank = params[:blank]
  	@no_price = params[:no_price]
  	if !@blank.blank?
	  	@offerings=Offering.includes(:products).where("products.id IS NULL").references(:products)
  	end
  	if !@no_price.blank?
	  	@offerings=Offering.where("price IS NULL")
  	end
  	if params[:sort_by] == "US_ASC"
  		@offerings=@offerings.sort_by {|o| o.orders.amzus.count }
  	elsif params[:sort_by] == "US_DESC"
  	  @offerings=@offerings.sort_by {|o| o.orders.amzus.count }.reverse
  	elsif params[:sort_by] == "NAME_ASC"
  	  @offerings=@offerings.sort_by {|o| o.name }.reverse
  	elsif params[:sort_by] == "NAME_DESC"
  	  @offerings=@offerings.sort_by {|o| o.name }
  	elsif params[:sort_by] == "CA_ASC"
  	  @offerings=@offerings.sort_by {|o| o.orders.amzca.count }
  	elsif params[:sort_by] == "CA_DESC"
  	  @offerings=@offerings.sort_by {|o| o.orders.amzca.count }.reverse
  	elsif params[:sort_by] == "WS_ASC"
  		@offerings=@offerings.sort_by {|o| o.orders.website.count }
  	elsif params[:sort_by] == "WS_DESC"
  		@offerings=@offerings.sort_by {|o| o.orders.website.count }.reverse
  	elsif params[:sort_by] == "BC_ASC"
  		@offerings=@offerings.sort_by {|o| o.orders.buy.count }
  	elsif params[:sort_by] == "BC_DESC"
  		@offerings=@offerings.sort_by {|o| o.orders.buy.count }.reverse
  	elsif params[:sort_by] == "PE_ASC"
  		@offerings=@offerings.sort_by {|o| o.orders.phone.count }
  	elsif params[:sort_by] == "PE_DESC"
  		@offerings=@offerings.sort_by {|o| o.orders.phone.count }.reverse
  	elsif params[:sort_by] == "EB_ASC"
  		@offerings=@offerings.sort_by {|o| o.orders.ebay.count }
  	elsif params[:sort_by] == "EB_DESC"
  		@offerings=@offerings.sort_by {|o| o.orders.ebay.count }.reverse
  	elsif params[:sort_by] == "ALL_ASC"
  		@offerings=@offerings.sort_by {|o| o.count }
  	elsif params[:sort_by] == "ALL_DESC"
  		@offerings=@offerings.sort_by {|o| o.count }.reverse
  	end
  	@offerings=@offerings.paginate(:page => params[:page], :per_page => 10)
  	
  end
  
private


    def offering_params
      params.require(:offering).permit(:name,:price, :sku, :sku_id, :sku_name, offering_products_attributes: [:id, :offering_id, :product_id, :product_name, :quantity], sku_attributes: [:id, :name])
    end
    
end

app/helpers/offerings_helper.rb
module OfferingsHelper
end

app/views/offerings/_offering_product_fields.html.erb
<p class="fields form-inline">
  <%= f.text_field :product_name, data: {autocomplete_source: autocomplete_products_path}, placeholder: "Product", class: "autocomplete offering_product" %>
  <%= f.text_field :quantity, class: "input-small", placeholder: "Quantity" %>
  <%= link_to_remove_fields "-", f %>
</p>
<script>
$(function() {
	 $( ".offering_product" ).autocomplete({
			source: $( "#offering_offering_products_attributes_0_product_name" ).data('autocomplete-source')
	});
});
</script>

app/views/offerings/_product_fields.html.erb
<p class="fields form-inline">
  <%= f.text_field :product_name, data: {autocomplete_source: autocomplete_products_path}, placeholder: "Product", class: "autocomplete" %>
  <%= f.text_field :quantity, class: "input-small", placeholder: "Quantity" %>
  <%= link_to_remove_fields "-", f %>
</p>
<script>
$(function() {
	 $( ".autocomplete" ).autocomplete({
			source: $( "#customer_orders_attributes_0_offering_name" ).data('autocomplete-source')
	});
});
</script>

app/views/offerings/_sort_button.html.erb
<%= form_tag(offerings_path, class: "form-inline", :style => "display:inline", method: :get) do %>
<%= hidden_field_tag :sort_by, input_name  %>
<%= hidden_field_tag :search, search  %>
<%= hidden_field_tag :blank, blank  %>
<button class="btn btn-mini" name="commit" type="submit">
		<i class="icon-chevron-<%= direction %>"></i>
</button>
<% end %>

app/views/offerings/_sort_buttons.html.erb
	<%= render "sort_button", input_name: "#{name}_ASC", direction: "up", search: search, blank: blank %>
	<%= render "sort_button", input_name: "#{name}_DESC", direction: "down", search: search, blank: blank %>

app/views/offerings/all.html.erb
<% Offering.all.each do |o| %>
	<%= o.name %><br>
<% end %>

app/views/offerings/edit.html.erb
<%= form_for @offering, :url=>{:controller=>"offerings", :action=>"replace"}, class: "form-inline" do |f| %>
		Replace with: 
		<%= f.text_field :name, data: {autocomplete_source: autocomplete_no_price_offerings_path}, placeholder: "Replace with", class: "autocomplete offering" %>
		<%= f.submit "Save", class: "btn btn-success" %>
<% end %>
<script>
$(function() {
	 $( ".offering" ).autocomplete({
			source: $( "#offering_name" ).data('autocomplete-source')
	});
});
</script>

<%= form_for @offering do |f| %>
	<div class="field">
		<%= f.label :name %>
		<%= f.text_area :name, size: "100x5" %>
	</div>
	<div class="field">
		<%= f.label :price %>
		<%= f.text_field :price %>
	</div>
		<div class="field">
		<%= f.label :sku_name %>
		<%= f.text_field :sku_name %>
	</div>
	<% n=1 %>
<h2>Products</h2>
	<%= f.fields_for(:offering_products, :html => { :class => "form-inline"}) do |builder| %>
	<%= render "offering_product_fields", :f => builder, show_offer: false %>
<% end %>
<p><%= link_to_add_fields "Add Product", f, :offering_products, false %></p>
<div class="actions">
	<%= f.submit "Save", class: "btn btn-success" %>
</div>
	<% end %>

app/views/offerings/index.html.erb
<table class="table" style="margin-bottom:0">
<tr>
<td><%= form_tag offerings_path, method: :get, class: "form-search form-inline" do %>
  	<%= text_field_tag :search, @search, placeholder: "Search Offerings", class: "search" %>
  	<%= submit_tag :submit, class: "btn" %>
<% end %></td>
<td>
<% if @blank.blank? %>
	<%= form_tag offerings_path, method: :get, class: "form-search form-inline" do %>
			<%= hidden_field_tag :search, @search %>
			<%= hidden_field_tag :blank, true %>
			<%= submit_tag :submit, value: "Display Offerings with no products", class: "btn" %>
	<% end %>
<% else %>
	<%= form_tag offerings_path, method: :get, class: "form-search" do %>
			<%= hidden_field_tag :search, @search %>
			<%= hidden_field_tag :blank, nil %>
			<%= submit_tag :submit, value: "Display All Offerings", class: "btn" %>
	<% end %>
<% end %>
</td>
<%
=begin %><td>
<% if @no_price.blank? %>
	<%= form_tag offerings_path, method: :get, class: "form-search form-inline" do %>
			<%= hidden_field_tag :search, @search %>
			<%= hidden_field_tag :no_price, true %>
			<%= submit_tag :submit, value: "Display Offerings with no price", class: "btn" %>
	<% end %>
<% else %>
	<%= form_tag offerings_path, method: :get, class: "form-search" do %>
			<%= hidden_field_tag :search, @search %>
			<%= hidden_field_tag :no_price, nil %>
			<%= submit_tag :submit, value: "Display All Offerings", class: "btn" %>
	<% end %>
<% end %>
</td>
<td>
<%= link_to "Orphaned Orders", orphans_orders_path, class: "btn" %></br>
</td>
<%
=end %>
<td>
<%= form_for offerings_path, url: {controller: :offerings, action: :add_price_csv, method: :patch} do |f| %>
  <%= f.file_field :file %>
  <%= f.submit "Load Price Data", class: "btn btn-primary" %>
<% end %>
</td>
<td>
<%= form_for offerings_path, url: {controller: :offerings, action: :add_sku_csv, method: :patch} do |f| %>
  <%= f.file_field :file %>
  <%= f.submit "Load SKU Data", class: "btn btn-primary" %>
<% end %>
</td>
</tr>
</table>
<%= link_to "Download to CSV", create_csv_offerings_path %><br>
<div class="pagination">
     <%= will_paginate @offerings, :container => false %>
</div>
</tr>
</table>
Entries shown: <%= @offerings.total_entries %>
<table class="table table-bordered table-striped table-condensed info">
	<tr>
	<td colspan="5"></td>
	<td colspan="7" style="text-align:center">Sales</td>
	</tr>
	<tr>
		<td style="width:80px">Modify</span></td>
		<td style="width:80px">SKU</span></td>
		<td style="text-align:center;width:250px">Offering Name<%= render "sort_buttons", name: "NAME", search: @search, blank: @blank %></td>
		<td style="text-align:center;width:60px">Price</td>
		<td style="text-align:center;width:60px">Weight (Lbs)</td>
		<td  style="text-align:center;width:150px">Included</td>
		<td style="text-align:center">AMZ US<br><%= render "sort_buttons", name: "US", search: @search, blank: @blank %></td>
		<td style="text-align:center">AMZ CAD<br><%= render "sort_buttons", name: "CA", search: @search, blank: @blank %></td>
		<td style="text-align:center">RBZ.COM<br><%= render "sort_buttons", name: "WS", search: @search, blank: @blank %></td>
		<td style="text-align:center">Buy<br><%= render "sort_buttons", name: "BC", search: @search, blank: @blank %></td>
		<td style="text-align:center">Ebay<br><%= render "sort_buttons", name: "EB", search: @search, blank: @blank %></td>
		<td style="text-align:center">Phone<br><%= render "sort_buttons", name: "PE", search: @search, blank: @blank %></td>
		<td style="text-align:center">All<br><%= render "sort_buttons", name: "ALL", search: @search, blank: @blank %></td>
	</tr>
	<style>
	form {
	margin:0;
	}
	</style>
<% @offerings.each do |offer| %>
	<tr>
	<td><%= link_to 'Edit', edit_offering_path(offer) %> | <%= link_to "Delete", offer, :method => :delete, :confirm => "You sure?",
                                :title => "Delete #{offer.name}" %></td>
  <td><%= offer.sku.blank? ? "" :offer.sku.name %></td>
  <td><%= link_to offer.name, offering_path(offer) %></td>
  <td>
  <div id="price_<%= offer.id %>">
		<% if offer.price.blank? %>
			<%= form_for offer, style: "display:inline;margin:0;padding:0;", remote: true do |f| %>
					<%= f.text_field :price, placeholder: "enter price", :class => "input-mini", style: "display:inline;margin:0" %>
			<% end %>
		<% else %>
		  <%= offer.price %>
		<% end %>
  </div>
  </td>
  <td><%= offer.total_weight %></td>
	<td>
		<ul>
		<% for product in offer.products %>
			<% if OfferingProduct.find_by_product_id_and_offering_id(product,offer).quantity %>
				<% if OfferingProduct.find_by_product_id_and_offering_id(product,offer).quantity > 0 %>
					<li><%= pluralize(OfferingProduct.find_by_product_id_and_offering_id(product,offer).quantity, product.name) %></li>
				<% end %>
			<% end %>
		<% end %>
		</ul>
	</td>
	<td class="number"><%= offer.orders.amzus.count %></td>
	<td class="number"><%= offer.orders.amzca.count %></td>
	<td class="number"><%= offer.orders.website.count %></td>
	<td class="number"><%= offer.orders.buy.count %></td>
	<td class="number"><%= offer.orders.ebay.count %></td>
	<td class="number"><%= offer.orders.phone.count %></td>
	<td class="number"><%= offer.orders.count %></td>
	</tr>
<% end %>
</table>

app/views/offerings/index.js.erb
$('.price#{@offer.id}').html('<%= @offer.price %>')

app/views/offerings/new.html.erb
<%= form_for @offering do |f| %>
	<div class="field">
		<%= f.label :name %><br />
		<%= f.text_field :name %>
	</div>
	<% n=1 %>
	<%= f.fields_for :offering_products do |po| %>  
		<div class="field">
			<%= Product.all.first(n).last.name %><br>
			<%= Product.all.first(n).last.description %><br>
			<%= pc.hidden_field :product_id, value: Product.all.first(n).last.id %>
			<%= pc.text_field :quantity %><br>
		<% n = n+1 %>
	<% end %> 
	<p><%= f.submit "Submit" %></p>
<% end %>

app/views/offerings/show.html.erb
<h1><%= @offering.name %></h1>
Total Weight: <%= @offering.total_weight %> lbs<br>
Current FBA Inventory: <%= amz_inventory=Offering.inventory([@offering.sku],"Amazon US")[@offering.sku] %><br>
<% y = Offering.amazon_sales_count(@offering.sku,"Amazon US")["y"] %><% d2 = Offering.amazon_sales_count(@offering.sku,"Amazon US")["dates"] %>
<% x = [] %>
<% d2.each_with_index do |d,i| %>
	<% x[i]=((d-d2[0])/7).to_f %>
<% end %>
<% lineFit = LineFit.new %>
<% lineFit.setData(x,y) %>
<% if x.length > 1 %>
	<% b, m = lineFit.coefficients %>
<% else %>
	<% b = 0 %>
	<% m = 0 %>
<% end %>
<% startY = x[0]*m+b %>
<% leadTime = 120 %>
<% leadTimeWeeks = (leadTime/7.0).ceil %>
<% endY = (x.last*m)+b %>
<% preY = (x.last+leadTimeWeeks)*m+b %>
<% prediction_x = ((x.last.round(0))..(x.last.round(0)+leadTimeWeeks)).to_a %>
<% prediction_y = prediction_x.map { |x| x*m+b } %>
<% sigma = lineFit.sigma %>
<div id="orders_chart"></div>
<script type="text/javascript" charset="utf-8">
  $(function () {
    new Highcharts.Chart({
     	chart: { renderTo: 'orders_chart' },
		  title: { text: 'Orders by week' },
		  xAxis: { 
		  	type: 'datetime',
				maxZoom: 14 * 24 * 3600000,
		  	text: "Week Number",
		  	min: Date.UTC(<%= d2.first.year %>,<%= d2.first.month-1 %>,<%= d2.first.day %>),
		  	max: Date.UTC(<%= (d2.last+leadTime).year %>,<%= (d2.last+leadTime).month-1 %>,<%= (d2.last+leadTime).day %>),
		  },
		  yAxis: {
		  	min: 0,
		    title: { text: 'Orders'}
		  },
		  series: [{
				name: 'Weekly Sales',
		    data: [ <% (0..(d2.length-1)).each do |n| %>
		    	[Date.UTC(<%= d2[n].year %>, <%= d2[n].month-1 %>, <%= d2[n].day %>), <%= y[n] %> ]<%= "," if n != (d2.length-1) %>
		    <% end %>
		    ]
		  },{
				type: 'line',
				name: 'Regression Line',
				data: [
					[Date.UTC(<%= d2.first.year %>, <%= d2.first.month-1 %>, <%= d2.first.day %>),<%= startY %>],
					[Date.UTC(<%= d2.last.year %>, <%= d2.last.month-1 %>, <%= d2.last.day %>),<%= endY %>]
				],
				marker: {
					enabled: false
				},
				states: {
					hover: {
						lineWidth: 0
					}
				},
				enableMouseTracking: false
			},{
				type: 'line',
				name: 'Plus Sigma',
				data: [
					[Date.UTC(<%= d2.first.year %>, <%= d2.first.month-1 %>, <%= d2.first.day %>),<%= startY+sigma %>],
					[Date.UTC(<%= (d2.last+leadTime).year %>, <%= (d2.last+leadTime).month-1 %>, <%= (d2.last+leadTime).day %>),<%= prediction_y.last+sigma %>]
				],
				marker: {
					enabled: false
				},
				states: {
					hover: {
						lineWidth: 0
					}
				},
				enableMouseTracking: false,
				dashStyle: 'Dash'
			},{
				type: 'line',
				name: 'Minus Sigma',
				data: [
					[Date.UTC(<%= d2.first.year %>, <%= d2.first.month-1 %>, <%= d2.first.day %>),<%= startY-sigma %>],
					[Date.UTC(<%= (d2.last+leadTime).year %>, <%= (d2.last+leadTime).month-1 %>, <%= (d2.last+leadTime).day %>),<%= prediction_y.last-sigma %>]
				],
				marker: {
					enabled: false
				},
				states: {
					hover: {
						lineWidth: 0
					}
				},
				enableMouseTracking: false,
				dashStyle: 'Dash'
			},{
				type: 'line',
				name: 'Prediction Line',
				data: [
					[Date.UTC(<%= d2.last.year %>, <%= d2.last.month-1 %>, <%= d2.last.day %>),<%= prediction_y.first %>],
					[Date.UTC(<%= (d2.last+leadTime).year %>, <%= (d2.last+leadTime).month-1 %>, <%= (d2.last+leadTime).day %>),<%= prediction_y.last %>]
					],
				marker: {
					enabled: false
				},
				dashStyle: 'Dash'
			}]
    });
  });
</script>
<% [28,90].each do |leadTime| %>
<h3><a href="#", style="color:#999">Assuming a <%= leadTime %> day lead time</a></h3>
<blockquote>
<% leadTimeWeeks = (leadTime/7.0).ceil %>
Current Inventory: <%= ci = amz_inventory %><br>
Sum of Orders Currently in the Pipeline: <% pl = 0 %><%= pl. round %><br>
Slope of the Demand Line: <%= m.round %><br>
Intercept of the Demand Line: <%= b.round %><br>
StDev of the Orders: <% sigma=lineFit.sigma %><%= sigma.round %><br>
StDev of the Demand for <%= leadTimeWeeks %> weeks: <% sdd=lineFit.sigma * Math.sqrt(leadTimeWeeks) %><%= sdd.round %><br>
Service level of 99% requires safety stock to be 2 sigma, so the safety stock level is: <% ss=sdd*2 %><%= ss.round %><br>
Predicted Demand:
<% weeks = (0..leadTimeWeeks).map { |w| w+y.length } %>
<% predictedDemand = weeks.map { |x1| m*x1+b } %>
<% pd= predictedDemand.sum - predictedDemand[0] %>
<%= pd.round %><br>
Need (Safety stock + Predicted Demand - (Current Inventory + Pipeline Orders))= <%= ss.round %> + <%= pd.round %> - (<%= ci.round %> + <%= pl.round %>) = <% need = (ss + pd - (ci+pl)) %><%= need.round %>peices <br>
</blockquote>
<% end %>

app/views/offerings/show.js.erb
$('.price_<%= @offer.id %>').html('<%= @offer.price %>')

app/views/offerings/update.js.erb
$('#price_<%= @offering.id %>').html('<%= @offering.price %>')