config/routes.rb
Inventory::Application.routes.draw do
  get "users/new"
	resources :users
	resources :sessions, only: [:new, :create, :destroy]
	
	get '/landing_page', to: 'static_pages#landing_page'
	get '/signup', to: 'users#new'
	get '/signin', to: 'sessions#new'
	delete '/signout', to: 'sessions#destroy', via: :delete
	
	resources :supplier_prices do
		collection do
			get :sort
		end
	end
	
	resources :suppliers do
		collection do
			get :autocomplete
		end
		member do
			post :csv
		end
	end
	
	resources :ship_terms do
		collection do
			get :autocomplete
		end
	end
	
	resources :customers do
		member do
			get :send_email
			get :send_oe_email
			get :send_customer_email
			get :new_order
		end
	end
	root to: 'static_pages#home'
	
	resources :products do
	member do
			get :cogs
		end
	collection do
			get :inventory_worksheet
			get :inventory_worksheet_print
			get :autocomplete
			get :monthly
			get :create_csv
			get :accounting_csv
			get :all_cogs
			get :canada_sales
			get :margin
			get :margin_csv
		end
	end
	resources :product_counts
	resources :skus do
		member do
			get :fees
		end
	end
	resources :events do
		collection do
			get :inventory
			get :amz_inventory
			get :po
			get :fba
			get :po_received
			get :new_inventory
			get :new_po
			post :load
			get :new_fba
			post :load_fba_shipment
			get :new_shipping_plan
			post :create_shipping_plan
		end
		member do
			get :receive_po_today
			get :edit_fba
			get :label
		end
	end
	resources :orders do
		member do
			post :replace
		end
		collection do
			get :new_phone
			get :create_phone
			post :create_single
		  post :destroy_range
			get :combo
			get :orphans
			post :load_data
		end
	end
	resources :offerings do
		member do
			patch :replace
		end
		collection do
				get :blank
				get :autocomplete
				get :autocomplete_sku
				get :autocomplete_no_price
				get :all
				post :add_price_csv
				post :add_sku_csv
				get :create_csv
		end
	end
end

app/models/event.rb
class Event < ActiveRecord::Base
  has_many :product_counts, :foreign_key => "event_id", :dependent => :destroy
  has_many :products, through: :product_counts
  has_many :offerings, through: :product_counts
  accepts_nested_attributes_for :product_counts, :reject_if => proc { |attributes| attributes['count'].blank?}, :allow_destroy => true
  belongs_to :supplier, :class_name => "Supplier"
  accepts_nested_attributes_for :supplier, :allow_destroy => true
  
  has_many :shipment_plans, class_name:  "ShipmentPlan",
                                  foreign_key: "plan_id",
                                  dependent:   :destroy
                                  
  has_many :shipments, through: :shipment_plans
  has_one :plan, through: :shipment_plans
  
  scope :inventory, -> { where(event_type: "Inventory") }
  scope :unreceived, -> { where(event_type: "Product Order", received: false) }
  scope :received, -> { where(event_type: "Product Order", received: true) }
  scope :product_orders, -> { where(event_type: "Product Order") }
  
  


def per_unit_cost
	count = 0
	product_counts.each do |pc|
		if pc.is_box
			count = count + pc.count * Product.find(pc.product_id).per_box
		else
			count = count +pc.count
		end
	end
	return (additional_cost ? additional_cost : 0) /count
end

def self.load_fba_shipment(infile,event_type,date,add_cost)
	i=0
	event=Event.create!(date: date, event_type: event_type, expected_date: date+1.month, received_date: date+1.month, received: false,additional_cost: add_cost)
	CSV.parse(infile, col_sep: "\t") do |row|
		if i == 0
			event.update_attributes(invoice: row[1])
		end
		if i>7
			#Merchant SKU		Title		ASIN		FNSKU		external-id		Condition		Shipped
			sku=Sku.where(name: row[0]).first_or_create
			ProductCount.create!(sku_id: sku.id,event_id: event.id,count: row[6], is_box: false)
		end
		i=i+1
	end
end

def self.update_inventory
	event=new(date: Date.today, event_type: "Inventory")
  inv=Product.get_sv_inventory
  Product.all.sort_by(&:name).each do |p|
    event.product_counts.build(attributes: { product_id: p.id, count: inv["#{p.id}"], is_box: false })
  end
  event.save!
end

def supplier_name
	supplier.try(:name)
end

def supplier_name=(name)
	self.supplier = Supplier.find_or_create_by(name: name) if name.present?
end

protected

    def check_product_count(product_count_attr)
			
      if product_count_attr['count'].blank?
      	rval ||= true
      else
      	rval ||= false
      end
      
      return rval
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
	#shipping plan
	
	def new_shipping_plan
	  origin=params[:origin]
	  @title="New Shipping Plan"
  	@show_offer = true
  	@event = Event.new(event_type: "Shipping Plan - #{origin}")
   	data=Sku.amazon(origin)
    data.sort_by { |a| a[0] }.each do |kit|
      sku=Sku.where(name: kit[0]).first
      need_28=sku.amazon_need(kit[1],origin,28).ceil
      if need_28>0
        @event.product_counts.build(sku_id: sku.id,count: need_28)
      end
    end
	end
	
	def create_shipping_plan
	  @event = Event.new(event_params)
	  @event.save!
    origin=@event.event_type[("Shipping Plan - ".length)..@event.event_type.length]
    fis=Sku.fulfillment_inbound_shipment_client(origin)
    ship_from_address={
      "PostalCode"=>"27217", 
      "Name"=>"OE Enterprises", 
      "CountryCode"=>"US", 
      "StateOrProvinceCode"=>"NC", 
      "AddressLine1"=>"717 N Park Ave", 
      "City"=>"Burlington"}
    inbound_shipment_plan_request_items=[]
    @event.product_counts.sort_by { |a| a.sku.name }.each do |pc|
      if pc.count>0
        inbound_shipment_plan_request_items << {"SellerSKU"=>pc.sku.name,"Quantity"=> pc.count.to_i}
      end
    end
    isp=fis.create_inbound_shipment_plan(ship_from_address, inbound_shipment_plan_request_items, label_prep_preference: "SELLER_LABEL")
    shipments=isp.parse["InboundShipmentPlans"]["member"]
    inbound_shipment=[]
    shipment_event=[]
    shipments.each_with_index do |shipment,i|
      shipment_id=shipment["ShipmentId"]
      shipment_city=shipment["ShipToAddress"]["City"]
      destination_fulfillment_center_id=shipment["DestinationFulfillmentCenterId"]
      inbound_shipment_header= {
        "ShipmentName" => "#{Date.today} - #{shipment_city}",
        "ShipFromAddress" => ship_from_address,
        "DestinationFulfillmentCenterId" => destination_fulfillment_center_id,
        "LabelPrepPreference" => "SELLER_LABEL",
        "ShipmentStatus" => "WORKING"
      }
      inbound_shipment_items=shipment["Items"]["member"]
      inbound_shipment_items.each {|s| s["QuantityShipped"]=s["Quantity"]; s.delete("Quantity")}
      inbound_shipment=fis.create_inbound_shipment(shipment_id, inbound_shipment_header, inbound_shipment_items: inbound_shipment_items)
      @shipment_event[i]=Event.new(event_type: origin, date: Date.today, expected_date: Date.today+30,received_date: Date.today+30,invoice: shipment_id)
      @shipment_event[i].save!
      inbound_shipment_items.each do |item|
        count=shipment_event[i].product_counts.new(sku: Sku.where(name: item["SellerSKU"]).first, count: item["Quantity"])
        count.save!
      end
    end
    
	end
	
	def shipment_details
	  event=Event.find(params[:id])
	end
	
	def label
    require 'barby'
    require 'barby/barcode/code_128'
    require 'barby/outputter/html_outputter'
    event=Event.find(params[:id])
    origin=event.event_type[("Shipping Plan - ".length)..event.event_type.length]
    pc=Sku.products_client(origin)
    @items=Hash.new()
    event.product_counts.sort_by { |a| a.sku.name }.each do |product|
      sku=product.sku
      if product.count>0
        product_info=pc.list_matching_products(kit[1]["ASIN"]).parse["Products"]
        @items[kit[0]]= {
          "Quantity"=> need_28, 
          "FNSKU" => kit[1]["FNSKU"], 
          "barcode" => Barby::Code128A.new(kit[1]["FNSKU"]),
          "Name" => product_info.blank? ? kit[0] : product_info["Product"]["AttributeSets"]["ItemAttributes"]["Title"]}
      end
    end
    render layout: false
  end
	
	def new
		@event=Event.new
		Product.all.count.times do
    	question = @event.product_counts.build
  	end
  end
  
  def load
    date = Date.new(params[:date]["day(1i)"].to_i,params[:date]["day(2i)"].to_i,params[:date]["day(3i)"].to_i)
		ProductCount.import(params[:file],date)
    redirect_to inventory_events_path, notice: "Inventory Loaded."
	end

	def amz_inventory
		@title="Amazon Inventory"
		@origin=params[:origin] || "Amazon US"
	end
  
  def new_inventory2
  	@event=Event.new
  	@event.event_type="Inventory"
  	@title="Inventory Log"
  	@subtitle=""
  	i=0;
  	@products=Array.new;
		Product.all.sort_by(&:name).each do |p|
    	@products[i] = @event.product_counts.build(attributes: { product_id: p.id })
    	i=i+1;
  	end
  	render :new
  end
  
  def new_inventory
  	event=Event.new(date: Date.today, event_type: "Inventory")
  	inv=Product.get_sv_inventory
  	Product.all.sort_by(&:name).each do |p|
    	event.product_counts.build(attributes: { product_id: p.id, count: inv["#{p.id}"], is_box: false })
  	end
  	event.save!
  	redirect_to inventory_events_path
  end
  
  def new_po
  	@event=Event.new(expected_date: Date.today+120,received_date: Date.today+120)
  	@event.event_type="Product Order"
  	@title="New Product Order"
  	@subtitle=""
  	@show_offer = false
   	question = @event.product_counts.build
  end
  
  def load_fba_shipment
  	infile = params[:event][:file].read
  	origin = params[:event][:event_type]
  	date=Date.new(params[:event]["date(1i)"].to_i,params[:event]["date(2i)"].to_i,params[:event]["date(3i)"].to_i)
  	add_cost=params[:event][:additional_cost]
  	Event.load_fba_shipment(infile,origin,date,add_cost)
		flash[:success] = "Shipment Loaded"
		redirect_to fba_events_path
  end
  
  def new_fba
  	@event=Event.new(expected_date: Date.today+30,received_date: Date.today+30)
  	@title="New Inventory Transfer"
  	@subtitle=""
  	@show_offer = true
   	question = @event.product_counts.build
  end

  
  def edit_fba
  	@event=Event.find(params[:id])
  	@show_offer = true
  	@title = "Edit Event"
  end
  
  def receive_po_today
  	@event=Event.find(params[:id])
  	if @event.update_attributes(received_date: Date.today, received: true)
  		flash[:success] = "Purchase Order Received"
  	else
  		flash[:error] = "Purchase Order Was Not Received"
  	end
  	if @event.event_type="Purchase Order"
  		redirect_to po_events_path
  	else
			redirect_to fba_events_path
  	end
  end
  
  def inventory
  	if params[:date_id]
		  @date = Event.find(params[:date_id])
		else
  	  @date = Event.inventory.sort_by(&:date).last
  	end
  	@events=Event.inventory.where(date: @date.date).paginate(:page => params[:page], :per_page => 1)
  	@title= @events.first.event_type
  	render :index
  end
  
  def destroy
  	session[:last_page] = request.env['HTTP_REFERER'] || po_events_url
  	@event=Event.find(params[:id])
  	event_type=@event.event_type
  	@event.destroy
  	redirect_to session[:last_page]
  end
  
  def fba
  	@title="FBA Shipments"
  	@events=Event.where("event_type LIKE ? OR event_type LIKE ?","Amazon Canada", "Amazon US").sort_by(&:created_at).reverse
  	@events=@events.paginate(:page => params[:page], :per_page => 10)
  end
  
  def po
  	@event_type=params[:event_type]
  	if @event_type == "All Shipments"
  		received=""
  	elsif @event_type == "Received"
			received="received = true AND "
  	elsif @event_type == "In Transit"
  		received="received = false AND"
    elsif @event_type == "Late"
  		received="received = false AND expected_date < ? AND"
  	else
  		received=""
  	end
  	@inv_num= params[:Invoice]? params[:Invoice] : ""
  	@sup_name= params[:Supplier]? params[:Supplier] : ""
  	if @event_type == "Late"
    	if @sup_name.length > 0
    		@supplier = Supplier.where("LOWER(name) LIKE ?","%#{@sup_name.downcase}%").first
			  @events=Event.where("#{received} LOWER(invoice) LIKE ? AND supplier_id = ? AND event_type='Product Order'",Date.today,"%#{@inv_num.downcase}%",@supplier.id)
		  else
			  @events=Event.where("#{received} LOWER(invoice) LIKE ? AND event_type='Product Order'",Date.today,"%#{@inv_num.downcase}%")
		  end
		else
		  if @sup_name.length > 0
    		@supplier = Supplier.where("LOWER(name) LIKE ?","%#{@sup_name.downcase}%").first
			  @events=Event.where("#{received} LOWER(invoice) LIKE ? AND supplier_id = ? AND event_type='Product Order'","%#{@inv_num.downcase}%",@supplier.id)
		  else
			  @events=Event.where("#{received} LOWER(invoice) LIKE ? AND event_type='Product Order'","%#{@inv_num.downcase}%")
		  end
		end
		if @inv_num == ""
			@inv_num=[]
		end
		if @sup_name == ""
			@sup_name=[]
		end
  	if params[:sort_by] == "INV_ASC"
  		@events=@events.sort_by {|a| a.invoice }.reverse
  	elsif params[:sort_by] == "INV_DESC"
  		@events=@events.sort_by {|a| a.invoice }
  	elsif params[:sort_by] == "SUP_ASC"
  		@events=@events.sort_by {|a| a.supplier.blank? ? "" : a.supplier.name }.reverse
  	elsif params[:sort_by] == "SUP_DESC"
  		@events=@events.sort_by {|a| a.supplier.blank? ? "" : a.supplier.name }
  	elsif params[:sort_by] == "DC_ASC"
  		@events=@events.sort_by {|a| a.date }.reverse
  	elsif params[:sort_by] == "DC_DESC"
  		@events=@events.sort_by {|a| a.date }
  	elsif params[:sort_by] == "DE_ASC"
  		@events=@events.sort_by {|a| a.expected_date }.reverse
  	elsif params[:sort_by] == "DE_DESC"
  		@events=@events.sort_by {|a| a.expected_date }
  	elsif params[:sort_by] == "DA_ASC"
  		@events=@events.sort_by {|a| a.received_date }.reverse
  	elsif params[:sort_by] == "DA_DESC"
  		@events=@events.sort_by {|a| a.received_date }
  	end
  	@title= "Product Order"
  	@events=@events.paginate(:page => params[:page], :per_page => 10)
  	render :index
  end
  
  def index
    if params[:get_count]
      @po = {quantity: Event.where(event_type: "Product Order").count}.to_xml
    else
      order_count=params[:order_count].to_f
			page=params[:page].to_f
			start=page*order_count+1
			finish=[(page+1)*order_count,Event.where(event_type: "Product Order").count].min
      @po = Event.where(event_type: "Product Order").first(finish).last((finish-start)+1).to_xml(only: 
        [:date, :date,:received_date,:received,:expected_date, :additional_cost, :invoice], 
        include: {supplier: {only: [:name]}, product_counts: {only: [:product_name, :count, :price], include: {product: {only: :sku }}}}, :skip_instruct => false)
    end
    respond_to do |format|
      format.xml { render xml: @po, :layout => false }

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_product_count_fields.html.erb
<p class="fields form-inline">
<% if show_offer %>
	<%= f.text_field :sku_name, data: {autocomplete_source: autocomplete_sku_offerings_path}, placeholder: "Kit SKU", class: "autocomplete" %>
<% else %>
  <%= f.text_field :product_name, data: {autocomplete_source: autocomplete_products_path}, placeholder: "Product", class: "autocomplete" %>
<% end %>
  <%= f.text_field :count, class: "input-small", placeholder: "Quantity" %>
  <%= f.hidden_field :is_box, value: false %> pieces 
  <% if @event.event_type == "Product Order" %>
  <%= f.text_field :price, placeholder: "Price" %>
  <% end %>
  <%= link_to_remove_fields "-", f %>

</p>
<% if show_offer %>
<script>
$(function() {
	$( ".autocomplete" ).autocomplete({
			source: $( "#event_product_counts_attributes_0_sku_name" ).data('autocomplete-source')
	});
});

</script>
<% else %>
<script>
$(function() {
	 $( ".autocomplete" ).autocomplete({
			source: $( "#event_product_counts_attributes_0_product_name" ).data('autocomplete-source')
	});
});

</script>
<% end %>

app/views/events/_sort_buttons.html.erb
	<%= render "sort_button", input_name: "#{name}_ASC", direction: "up", inv_num: inv_num, sup_name: sup_name, event_type: event_type %>
	<%= render "sort_button", input_name: "#{name}_DESC", direction: "down", inv_num: inv_num, sup_name: sup_name, event_type: event_type %>

app/views/events/amz_inventory.html.erb
<h1>FBA Inventory</h1>
	<%= form_tag(amz_inventory_events_path, method: :get) do %>
    <%= select_tag :origin, options_for_select(["Amazon US", "Amazon Canada","Amazon UK","Amazon UK"], @origin) %>
    <%= submit_tag "Select Country",class: "btn" %>
<% end %>
<%= link_to "Create New Shipping Plan", new_shipping_plan_events_path(origin: @origin) %>
<%= render "amz_table", origin: @origin %>

app/views/events/edit.html.erb
<%= form_for @event do |f| %>
	<p><%= f.hidden_field :event_type, value: @event.event_type %>
		<%= f.label :date %>
		<%= f.date_select :date, {order: [:month, :day, :year]}, {:class => "input-small"}  %>
	<% if @event.event_type == "Product Order" %>
		<%=f.label :invoice, "Invoice # (PO#):" %>
		<%= f.text_field :invoice %>
		<%= f.label :supplier_name %>
		<%= f.text_field :supplier_name, data: {autocomplete_source: autocomplete_suppliers_path}, placeholder: "Supplier", class: "autocomplete_sup" %>
		<%= f.label :expected_date %>
		<%= f.date_select :expected_date, {order: [:month, :day, :year]}, {:class => "input-small"}  %>
		<%= f.label :received_date %>
		<%= f.date_select :received_date, {order: [:month, :day, :year]}, {:class => "input-small"} %><br>
		<%= f.radio_button :received, "true" %> received
		<%= f.radio_button :received, "false" %> not yet received
		<%= f.label :additional_cost %>
		<%= f.text_field :additional_cost %>
	<% end %>
	</p>
	<% n=0 %>
		<h2>Products</h2>
	<%= f.fields_for :product_counts do |builder| %>  
		<%= render "product_fields", f: builder, product: @products[n].product, event: @event %>
		<% n = n+1 %>
	<% end %>
	<center><div style="width:500px"><%= f.submit "Submit", style: "width:200px;height:50px;font-size:40px;text-align:center" %></div></center>
<% end %>

	
	<script>
$(function() {
	 $( ".autocomplete_sup" ).autocomplete({
			source: $( ".autocomplete_sup" ).data('autocomplete-source')
	});
});

</script>

app/views/events/fba.html.erb
<%= form_for :event, url: {controller: "events", action: "load_fba_shipment", class: "form-inline"} do |f| %>
<table class="table">
	<tr>
		<th>Select Shipment File:</th>
		<th>Setup Date:</th>
		<th>Additional Cost:</th>
		<th>Shipment Going to:</th>
	<th></th>
	</tr>
	<tr>
		<td><%= f.file_field :file %></td>
		<td><%= f.date_select :date, { :order => [:month, :day, :year]}, {:class => "input-small"} %></td>
		<td><%= f.text_field :additional_cost %></td>
		<td><%= f.select :event_type, options_for_select(["Amazon US", "Amazon Canada"]) %></td>
		<td><%= f.submit "Load Data", class: "btn btn-primary" %></td>
	</tr>
</table>
<% end %>
<%= link_to 'Manually load FBA Shipment', new_fba_events_path %> 
	<div class="pagination">
		<%= will_paginate @events, :container => false %>
	</div>
<table class="table table-bordered table-striped table-condensed">
	<thead>
		<tr>
			<th style="vertical-align:top;text-align:center">Modify Record</th>
			<th style="vertical-align:top;text-align:center">Location</th>
			<th style="vertical-align:top;text-align:center">Dates</th>
			<th style="vertical-align:top;text-align:center">Invoice</th>
			<th style="vertical-align:top;text-align:center">Products</th>
			<th style="vertical-align:top;text-align:center">Shipping and Handling</th>
		</tr>
	</thead>
	<tbody>
	<% @events.each do |event| %>
		<tr>
			<td><%= link_to 'Edit', edit_fba_event_path(event) %> | <%= link_to "Delete", event, :method => :delete, data: {confirm: "You sure?"}, :title => "Delete #{event.event_type}" %> | <%= link_to 'Receive Today', receive_po_today_event_path(event) %> 
			</td>
			<td><%= event.event_type %></td>
			<td>Created: <%= event.date %><br>
			Expected: <%= event.expected_date %><br>
			<%= "Received: #{event.received_date}" if event.received %></td>
			<td><%= event.invoice %></td>
			<td>
				<table class="table">
					<% event.product_counts.sort_by(&:sku_name).each do |pc| %>
						<tr>
							<td><%= link_to pc.sku.name, {controller: 'skus', action:"show", id: pc.sku.id, origin: event.event_type} %></td>
							<td><%= pc.count.round %> peices</td>
						</tr>
					<% end %>
				</table>
			</td>
			<td><%= event.additional_cost %></td>
		</tr>
	<% end %>
	</tbody>
</table>
	<div class="pagination">
		<%= will_paginate @events, :container => false %>
	</div>

app/views/events/index.html.erb
<% if @title == "Product Order" %>
	Search:
	<%= form_tag(po_events_path, method: :get) do %>
		<table class="table-condensed">
			<tr>
				<td>Invoice #:</td>
				<td>Supplier Name:</td>
				<td>Delivery Status:</td>
				<td></td>
			</tr>
			<tr style="vertical-align:middle;">
				<td style="vertical-align:top;">
					<%= text_field_tag :Invoice, @inv_num, placeholder: "Invoice #" %>
				</td>
				<td style="vertical-align:top;">
					<%= text_field_tag :Supplier, @sup_name, placeholder: "Supplier Name", data: {autocomplete_source: autocomplete_suppliers_path}, class: "autocomplete_sup" %>
				</td>
				<td style="vertical-align:top;">
					<%= select_tag :event_type, options_for_select(["All Shipments", "Received", "In Transit","Late"], @event_type) %>
				</td>
				<td style="vertical-align:top;">
					<%= submit_tag "Submit", class: "btn btn-primary" %>
				</td>
			</tr>
		</table>
	<% end %>
	<script>
		$(function() {
			$( ".autocomplete_sup" ).autocomplete({
				source: $( ".autocomplete_sup" ).data('autocomplete-source')
			});
		});
	</script>
	<%= link_to "New Product Order", new_po_events_path %>
	<div class="pagination">
		<%= will_paginate @events, :container => false %>
	</div>
<% elsif @title == "Inventory" %>
	<%= link_to "New Inventory Count", new_inventory_events_path %>
	<%= form_tag inventory_events_path, method: :get, class: "form-search form-inline" do  %>
		<%= select_tag :date_id, options_for_select(Event.inventory.sort_by(&:date).collect {|a| [a.date, a.id]}, @date.id), class: "input-medium" %>
		<%= submit_tag %>
	<% end %>
<% end %>


<table class="table table-bordered table-striped table-condensed">
	<thead>
		<tr>
			<th style="vertical-align:top;text-align:center">Modify Record</th>
			<th style="vertical-align:top;text-align:center">
				Date Created<br>
				<%= render "sort_buttons", name: "DC", inv_num: @inv_num, sup_name: @sup_name, event_type: @event_type %>
			</th>
			<% if @title == "Product Order" %>
				<th style="vertical-align:top;text-align:center">
					Invoice num<br>
					<%= render "sort_buttons", name: "INV", inv_num: @inv_num, sup_name: @sup_name, event_type: @event_type  %>
				</th>
				<th style="vertical-align:top;text-align:center">
					Supplier<br>
					<%= render "sort_buttons", name: "SUP", inv_num: @inv_num, sup_name: @sup_name, event_type: @event_type  %>
				</th>
				<th style="vertical-align:top;text-align:center">
					Expected Delivery<br>
					<%= render "sort_buttons", name: "DE", inv_num: @inv_num, sup_name: @sup_name, event_type: @event_type  %>
				</th>
				<th style="vertical-align:top;text-align:center">
					Actual Delivery<br>
					<%= render "sort_buttons", name: "DA", inv_num: @inv_num, sup_name: @sup_name, event_type: @event_type  %>
				</th>
			<% elsif @title != "Inventory" %>
				<th style="vertical-align:top;text-align:center">
					Expected Delivery<br>
					<%= render "sort_buttons", name: "DE", inv_num: @inv_num, sup_name: @sup_name, event_type: @event_type  %>
				</th>
				<th style="vertical-align:top;text-align:center">
					Actual Delivery<br>
					<%= render "sort_buttons", name: "DA", inv_num: @inv_num, sup_name: @sup_name, event_type: @event_type  %>
				</th>
			<% end %>
			<th style="vertical-align:top;text-align:center">
				Products
			</th>
		</tr>
	</thead>
	<tbody>
		<% @events.each do |event| %>
			<tr>
				<td>
					<%= link_to 'Edit', edit_event_path(event) %> | <%= link_to "Delete", event, :method => :delete, data: {confirm: "You sure?"}, :title => "Delete #{event.event_type}" %> 
					<% if !event.received && @title != "Inventory" %>
						| <%= link_to 'Receive Today', receive_po_today_event_path(event) %> 
					<% end %>        
				</td>
				<td><%= event.date %></td>
				<% if @title == "Product Order" %>
					<td><%= event.invoice %></td>
					<td><%= event.supplier.blank? ? "" : (link_to event.supplier.name, supplier_path(event.supplier)) %></td>
					<td><%= event.expected_date %></td>
					<td><%= event.received_date if event.received %></td>
				<% end %>
				<td>
					<table class="table">
						<% event.product_counts.sort_by(&:product_name).each do |pc| %>
							<tr>
									<td><%= link_to pc.product.name, product_path(pc.product) %></td>
									<td>
										<% if event.event_type == "Inventory" %>
											<%= pc.count.round %> peices
											<% if pc.count > 0 %>
												[<%= "#{pc.box_count.round} boxes" if pc.box_count.round>0 %><%= " #{pc.piece_count.round} pieces" if pc.piece_count.round>0 %>]
											<% else %>
												[0 boxes]
											<% end %>
										<% else %>
											<%= pc.count.round %> 
											<% if pc.is_box %>
												boxes
											<% else %>
												pieces
											<% end %>
										<% end %>
									</td>
									<% if @title != "Product Order" %>
										<td><%= number_to_currency(pc.product.get_value(event)) %></td>
									<% end %>
							</tr>
						<% end %>
						<% if @title == "Inventory"  %>
							<tr>
								<td></td><td>Total:</td>
								<td><%= number_to_currency(Product.total_inventory_value(event)) %></td>
							</tr>
						<% end %>
					</table>
				</td>
			</tr>
		<% end %>
	</tbody>
</table>
<% if @title == "Product Order" %>
	<div class="pagination">
		<%= will_paginate @events, :container => false %>
	</div>
<% end %>