config/routes.rb
Inventory::Application.routes.draw do
  get "users/new"
	resources :users
	resources :sessions, only: [:new, :create, :destroy]
	
	get '/landing_page', to: 'static_pages#landing_page'
	get '/signup', to: 'users#new'
	get '/signin', to: 'sessions#new'
	delete '/signout', to: 'sessions#destroy', via: :delete
	
	resources :supplier_prices do
		collection do
			get :sort
		end
	end
	
	resources :suppliers do
		collection do
			get :autocomplete
		end
		member do
			post :csv
		end
	end
	
	resources :ship_terms do
		collection do
			get :autocomplete
		end
	end
	
	resources :customers do
		member do
			get :send_email
			get :send_oe_email
			get :send_customer_email
			get :new_order
		end
	end
	root to: 'static_pages#home'
	
	resources :products do
	member do
			get :cogs
		end
	collection do
			get :inventory_worksheet
			get :inventory_worksheet_print
			get :autocomplete
			get :monthly
			get :create_csv
			get :accounting_csv
			get :all_cogs
			get :canada_sales
			get :margin
			get :margin_csv
		end
	end
	resources :product_counts
	resources :skus do
		member do
			get :fees
		end
	end
	resources :events do
		collection do
			get :inventory
			get :amz_inventory
			get :po
			get :fba
			get :po_received
			get :new_inventory
			get :new_po
			post :load
			get :new_fba
			post :load_fba_shipment
			get :new_shipping_plan
			post :create_shipping_plan
		end
		member do
			get :receive_po_today
			get :edit_fba
			get :label
		end
	end
	resources :orders do
		member do
			post :replace
		end
		collection do
			get :new_phone
			get :create_phone
			post :create_single
		  post :destroy_range
			get :combo
			get :orphans
			post :load_data
		end
	end
	resources :offerings do
		member do
			patch :replace
		end
		collection do
				get :blank
				get :autocomplete
				get :autocomplete_sku
				get :autocomplete_no_price
				get :all
				post :add_price_csv
				post :add_sku_csv
				get :create_csv
		end
	end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

	def new
		@product = Product.new
		@title = "New Product"
	end

	def inventory_worksheet
		@products = Product.all.sort_by { |a| a.name }
		if params[:start_date_id]
		@start_date = Event.find(params[:start_date_id])
  	@end_date = Event.find(params[:end_date_id])
		else
 		@start_date = Event.inventory.sort_by(&:date).last(2).first
  	@end_date = Event.inventory.sort_by(&:date).last
  	end
		@title = "Inventory Worksheet"
	end
	
	def inventory_worksheet_print
		@products = Product.all.sort_by { |a| a.name }
		@title = "Print Inventory Worksheet"
		render "products/inventory_worksheet", layout: false
	end
	
	def create
		@product = Product.new(product_params)
    @product.save
    redirect_to products_path
	end
	
	def cogs
		@product = Product.find(params[:id])
    if params[:start_date]
  		@start_date = Date.new(params[:start_date][:year].to_i,params[:start_date][:month].to_i,params[:start_date][:day].to_i)
  		@end_date = Date.new(params[:end_date][:year].to_i,params[:end_date][:month].to_i,params[:end_date][:day].to_i)
  	else
  		@start_date = Date.today.beginning_of_year
  		@end_date = Date.today.end_of_year
  	end
  	output = @product.cogs(@start_date,@end_date)
  	@value=output[:value]
		@orders=output[:purchases]
		respond_to do |format|
      format.js
    end
	end
	
	def create_csv
		inv=Product.get_sv_inventory
		csv = CSV.generate(col_sep: "\t") do |csv|
			csv << ["name", "Current Inventory","Reorder Point","Average Lead Time","quantity per box", "60 day need", "90 day need", "120 day need"]
			Product.where(display:true).sort_by(&:id).each do |product|
				csv << [product.name, inv[product.id], product.reorder_point.round, product.averageLeadTime.round, product.per_box, product.need(60,inv[product.id]).round, product.need(90,inv[product.id]).round, product.need(120,inv[product.id]).round]
			end
		end
		file ="inventory.txt"
		File.open(file, "w"){ |f| f << csv }
		send_file( file, type: 'text/csv')
	end
	
	def accounting_csv
		start_date = Date.new(1990,1,1)
		end_date = Date.today
		csv = CSV.generate(col_sep: "\t") do |csv|
			csv << ["Name", "Total Sales", "Total Cost of Goods Sold", "Average Inventory", "Average Price"]
			Product.where(display:true).sort_by(&:name).each do |product|
				output = product.cogs(start_date,end_date)
				csv << [product.name, output[:purchases], output[:value], product.average_inventory(start_date,end_date), product.avg_price]
			end
		end
		file ="accounting.txt"
		File.open(file, "w"){ |f| f << csv }
		send_file( file, type: 'text/csv')
	end
	
	def margin_csv
	  start_date = Date.today - 6.months
		end_date = Date.today
		csv = CSV.generate(col_sep: "\t") do |csv|
			csv << ["Product Name", "Product Cost", "Average Retail Price", "Margin", "Total Sales"]
			Product.where(display: true).sort_by(&:name).each do |product|
				output = product.cogs(start_date,end_date)
        if output[:purchases] > 0
				  csv << [product.name, output[:value]/output[:purchases], product.avg_price, product.avg_price-output[:value]/output[:purchases], output[:purchases]]
				end
			end
		end
		file ="margins.txt"
		File.open(file, "w"){ |f| f << csv }
		send_file( file, type: 'text/csv')
	end
	
	def edit
		@title = "Edit Product"
		@product = Product.find(params[:id])
		if @product.supplier_prices.count == 0
			@product.supplier_prices.build
		end
	end

	def autocomplete
		@products = Product.search(params[:term])
		render json: @products.map(&:name)
	end
	
	def update
		@product = Product.find(params[:id])
  	if @product.update_attributes(product_params)
  		flash[:success]= "Product Updated"
  		redirect_to @product
  	else
  		render 'edit'
  	end
	end
	
	def all_cogs
		@title ="Cost of Goods Sold"
		if params[:start_date]
  		@start_date = Date.new(params[:start_date][:year].to_i,params[:start_date][:month].to_i,params[:start_date][:day].to_i)
  		@end_date = Date.new(params[:end_date][:year].to_i,params[:end_date][:month].to_i,params[:end_date][:day].to_i)
  	else
  		@start_date = Date.today.beginning_of_year
  		@end_date = Date.today.end_of_year
  	end
  	@product={}
		@value={}
		@orders={}
		@avg={}
		@value_total=0
		@orders_total=0
  	Product.all.sort_by(&:id).each_with_index do |product,i|
  		output=product.cogs(@start_date,@end_date)
  		@product[i]=product
			@value[i]=output[:value]
			@orders[i]=output[:purchases]
			@value_total=@value[i]+@value_total
			@orders_total=@orders[i]+@orders_total
  	end
	end
	def margin
	  @start_date = Date.today - 6.months
    @end_date = Date.today
    @title = "Product Margins"
	  @products=Product.where(display: true).sort_by(&:name).paginate(:page => params[:page], :per_page => 10)
	end
	
	def show
    @product = Product.find(params[:id])
    @supplier_prices=@product.supplier_prices
    @title = @product.name
    if params[:start_date]
  		@start_date = Date.new(params[:start_date][:year].to_i,params[:start_date][:month].to_i,params[:start_date][:day].to_i)
  		@end_date = Date.new(params[:end_date][:year].to_i,params[:end_date][:month].to_i,params[:end_date][:day].to_i)
  	else
  		@start_date = Date.today.beginning_of_year
  		@end_date = Date.today
  	end
  	output = @product.cogs(@start_date,@end_date)
  	@value=output[:value]
		@orders=output[:purchases]
		@ido=@product.inventory_days_outstanding(@start_date,@end_date)
		@it=@product.inventory_turns(@start_date,@end_date)
		@avg_price=@product.avg_price
		@margin=@product.margin(@start_date,@end_date)
  end
	
	def index
		@title = "All Products"
    @products = Product.where(display: true).sort_by { |a| a.name }.paginate(:page => params[:page], :per_page => 10)
	end
	
	def destroy
    Product.find(params[:id]).destroy
    redirect_to products_path 
  end
  
  
private


    def product_params
      params.require(:product).permit(:name,:description,:per_box,:imloc,:weight,:display, :product_name,:price,:sku, supplier_prices_attributes: [:id,:date,:supplier_id,:product_id,:supplier_name,:product_name,:ship_term_term, :quantity, :price, '_destroy'],supplier_attributes: [:id, :supplier_name, :name, '_destroy'])
    end
    
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_nav.html.erb
<div style="float:left">
<%= link_to("< Previous", product_path(product.previous), class: "btn") if !product.previous.nil? %>
</div>
<div style="float:right">
<%= link_to("Next >", product_path(product.next), class: "btn") if !product.next.nil? %>
</div>

app/views/products/_product.html.erb
<% if product.running_out? %>
	<% c = 'error' %>
<% else %>
	<% c = '' %>
<% end %>
<tr class= "<%= c %>">
	<td>
		<%= link_to 'Edit', edit_product_path(product) %> | <%= link_to "delete", product, :method => :delete, :confirm => "You sure?",
                                :title => "Delete #{product.name}" %>
	</td>
	<td>
		<%= link_to product.name, product_path(product) %>
	</td>
	<td>
		<%= product.description %>
	</td>
	<td>
		<%= pluralize(product.weight,"lb") if product.weight && product.weight >0 %>
	</td>
	<td class="number">
		<%= product.per_box %>
	</td>
	<td class="number">
		<%= inv[product.id].round %>
	</td>
	<td class="number">
		<%= product.get_orders(1000).round %>
	</td>
	<td class="number">
		<% if product.need(60,inv[product.id]).round > 0 %>
			<span style="color:red;font-weight:bold">
		<% else %>
			<span>
		<% end %>
		<%= product.need(60,inv[product.id]).round %></span>
	</td>
	<td class="number">
		<% if product.need(90,inv[product.id]).round > 0 %>
			<span style="color:red;font-weight:bold">
		<% else %>
			<span>
		<% end %>
		<%= product.need(90,inv[product.id]).round %></span>
	</td>
	<td class="number">
	<% if product.need(120,inv[product.id]).round > 0 %>
			<span style="color:red;font-weight:bold">
		<% else %>
			<span>
		<% end %>
		<%= product.need(120,inv[product.id]).round %></span>
	</td>
</tr>

app/views/products/_sort_button.html.erb
<%= form_tag(sort_supplier_prices_path, class: "form-inline", :style => "display:inline", method: :get, remote: true) do %>
<%= hidden_field_tag :sort_by, input_name  %>
<%= hidden_field_tag :id, id  %>
<button class="btn btn-mini" name="commit" type="submit">
		<i class="icon-chevron-<%= direction %>"></i>
</button>
<% end %>

app/views/products/_sort_buttons.html.erb
	<%= render "products/sort_button", input_name: "#{name}_ASC", direction: "up", id: id %>
	<%= render "products/sort_button", input_name: "#{name}_DESC", direction: "down", id: id %>

app/views/products/_supplier_price_fields.html.erb
<p class="fields form-inline">
	<%= f.date_select :date, {order: [:month, :day, :year]}, {:class => "btn-mini input-mini"}  %>
  <%= f.text_field :ship_term_term, data: {autocomplete_source: autocomplete_ship_terms_path}, placeholder: "Shipping Terms", class: "input-small autocomplete_terms" %>
  <%= f.text_field :supplier_name, data: {autocomplete_source: autocomplete_suppliers_path}, placeholder: "Supplier", class: "input autocomplete_supplier" %>
  <%= f.text_field :quantity, placeholder: "Quantity", class: "input-mini" %>
  <%= f.text_field :price, placeholder: "Price", class: "input-mini" %>
  <%= link_to_remove_fields "-", f %>
</p>
<script>
$(function() {
	 $( ".autocomplete_supplier" ).autocomplete({
			source: $( "#product_supplier_prices_supplier_name" ).data('autocomplete-source')
	});
});
$(function() {
	 $( ".autocomplete_terms" ).autocomplete({
			source: $( "#product_supplier_prices_ship_term_term" ).data('autocomplete-source')
	});
});
</script>

app/views/products/all_cogs.html.erb
<div style="text-align:center;margin-left:auto;margin-right:auto;width:auto">
Time Span:
<%= form_tag(all_cogs_products_path, method: :get) do %>
<%= select_date @start_date, {:prefix => 'start_date'}, {:class => "btn-mini input-mini"} %> to <%= select_date @end_date, {:prefix => 'end_date'}, {:class => "btn-mini input-mini"} %><%= submit_tag "submit", :class => "btn btn-success" %>
<% end %>
</div>
<style>
table.table { width:auto;margin-left:auto;margin-right:auto }
td.num { text-align: center }
th.num { text-align: center }
</style>
<table class="table table-condensed table-bordered table-striped">
<thead>
<tr>
	<th>Product Name</th>
	<th class="num">Total Orders</th>
	<th class="num">Total COGS</th>
	<th class="num">Average COGS</th>
</tr>
</thead>
<tbody>
<% @product.each_with_index do |product,i| %>
<tr>
<td><%= @product[i].name %></td>
<td class="num"><%= number_with_precision(@orders[i], :precision => 0, :delimiter => ',') %></td>
<td class="num">$<%= number_with_precision(@value[i], :precision => 2, :delimiter => ',') %></td>
<td class="num">$<%= number_with_precision((@orders[i] > 0 ? @value[i]/@orders[i] : 0), :precision => 2, :delimiter => ',') %></td>
</tr>
<% end %>
<tr>
<td>Total</td>
<td class="num"><%= number_with_precision(@orders_total, :precision => 0, :delimiter => ',') %></td>
<td class="num">$<%= number_with_precision(@value_total, :precision => 2, :delimiter => ',') %></td>
<td class="num">$<%= number_with_precision((@orders_total > 0 ? @value_total/@orders_total : 0), :precision => 2, :delimiter => ',') %></td>
</tr>
</tbody>
</table>

app/views/products/show.html.erb
<%= render 'nav', product: @product %>
<br>
<table style="vertical-align:top; width:100%;table-layout: fixed;">
<tr valign="top">
<td style="width">
<%= image_tag @product.imloc, class: "product-image" %><br>
<%= link_to 'Edit', edit_product_path(@product) %> | <%= link_to "Delete", @product, :method => :delete, :confirm => "You sure?",
                                :title => "Delete #{@product.name}" %><br/>
<p><%= @product.sku %></p>
<p><%= @product.description %></p>
<p><%= @product.per_box %> pieces/box</p>

<p>Retail Price: <%= @product.price %></p>
<p>Shipping Weight: <%= @product.weight %></p>
<% y = @product.get_trend["y"] %>
<% d2 = @product.get_trend["dates"] %>
<% glc=@product.get_sv_inventory %> 
<div id="accordion">
<h2><a href="#", style="color:#999">Latest Inventory</a></h2>
<blockquote>
<% if glc>0 %>
Done on: <%= Date.today %> <br>
<%= glc %> pieces<br>
Value: <%=  number_to_currency(@product.get_value(Event.new(date: Date.today))) %> <br>
<% else %>
Done on: <b>never</b><br>
0 boxes
<% end %>
</blockquote>
<h2><a href="#", style="color:#999">Cost of Goods Sold</a></h2>
<blockquote>
Time Span:
<%= form_tag(cogs_product_path(@product), method: :get, remote: true) do %>
<%= select_date @start_date, {:prefix => 'start_date'}, {:class => "btn-mini input-mini"} %> to <%= select_date @end_date, {:prefix => 'end_date'}, {:class => "btn-mini input-mini"} %><%= submit_tag "submit", :class => "btn btn-success" %>
<% end %>
Total Orders During Period: <span id="orders"><%= number_with_precision(@orders, :precision => 0, :delimiter => ',') %></span><br>
Total Cost of Goods Sold During Period: <span id="cogs"><%= number_to_currency(@value) %></span><br>
<% if @orders > 0 %>
Average Cost of Goods Sold During Period: <span id="averagecogs"><%= number_to_currency(@value/@orders) %></span><br>
Inventory Days Outstanding: <span id="ido"><%= (@ido*100).round/100.00 %></span><br>
Inventory Turns: <span id="it"><%= (@it*100).round/100.00 %></span><br>
Average Price: <span id="averageprice"><%= number_to_currency(@avg_price) %></span><br>
Average Margin: <span id="averageprice"><%= number_to_currency(@margin) %></span><br>
<% end %>
</blockquote>

<h2><a href="#", style="color:#999">Supplier Prices</a></h2>
<blockquote>
<div id="supplier_prices"%>
<%= render 'supplier_prices', supplier_prices: @supplier_prices, id: @product.id %>
</blockquote>


<h2><a href="#", style="color:#999">Orders Currently Out</a></h2>
<blockquote>
<% oco = 0 %>
<table class="table">
	<tr>
		<th>Modify</th>
		<th>Made</th>
		<th>Expected</th>
		<th>Quantity (pcs)</th>
	</tr>
<% @product.get_current_shipments.each do |co| %>
	<% pc=co.product_counts.find_by_product_id(@product) %>
	<% if pc.count > 0 %>
		<% if co.expected_date < Date.today && !co.received && co.event_type == "Product Order" %>
			<tr class="error">
		<% else %> 
			<tr>
		<% end %>
		<td><%= link_to "edit", edit_event_path(co) %></td>
		<td><%= co.date %></td>
		<td><%= co.expected_date %></td>
		<td><%= pc.count %></td>
		<% oco = oco + pc.count %>
	</tr>
	<% end %>
<% end %>
</table>
<%= oco %><br>
</blockquote>
<h2><a href="#", style="color:#999">Purchase Orders Received</a></h2>
<blockquote>
<table class="table">
	<tr>
		<th>Modify</th>
		<th>Made</th>
		<th>Received</th>
		<th>Quantity (pcs)</th>
	</tr>
<% @product.get_received_shipments.each do |co| %>
	<% pc=co.product_counts.find_by_product_id(@product) %>
	<% if pc.count > 0 %>
		<tr>
		<td><%= link_to "edit", edit_event_path(co) %></td>
		<td><%= co.date %></td>
		<td><%= co.received_date %></td>
		<td><%= pc.count %></td>
	</tr>
	<% end %>
<% end %>
</table>
</blockquote>
<h2><a href="#", style="color:#999">Customer Orders</a></h2>
<blockquote>
<% n=0 %>
<% d2.each do |a| %>
	<%= d2[n] %> - <%= y[n] %> <br>
	<% n=n+1 %>
<% end %>
</blockquote>
<% if glc>0 && y.count>1 %>
	<% x = [] %>
	<% d2.each_with_index do |d,i| %>
		<% x[i]=((d-d2[0])/7).to_f %>
	<% end %>
	<% lineFit = LineFit.new %>
	<% lineFit.setData(x,y) %>
	<% if x.length > 1 %>
	<% b, m = lineFit.coefficients %>
<% else %>
	<% b = 0 %>
	<% m = 0 %>
<% end %>
<% startY = x[0]*m+b %>
<% leadTime = 120 %>
<% leadTimeWeeks = (leadTime/7.0).ceil %>
<% endY = (x.last*m)+b %>
<% preY = (x.last+leadTimeWeeks)*m+b %>
<% prediction_x = ((x.last.round(0))..(x.last.round(0)+leadTimeWeeks)).to_a %>
<% prediction_y = prediction_x.map { |x| x*m+b } %>
<% sigma = lineFit.sigma %>

<h2><a href="#", style="color:#999">Amount Needed to Order</a></h2>
<blockquote>
Reorder Point: <%= @product.reorder_point.round %> units
<div id="accordion1">
	<%= render "need_calc", product: @product, leadTime: 60, m: m, b: b, lineFit: lineFit, y: y %>
	<%= render "need_calc", product: @product, leadTime: 90, m: m, b: b, lineFit: lineFit, y: y %>
	<%= render "need_calc", product: @product, leadTime: 120, m: m, b: b, lineFit: lineFit, y: y %>
</div>
</blockquote>
</td>
<td style="vertical-align:top">
Orders current until the week of: <%= d2.last %>
<div id="orders_chart" style="width:560px; height:300px;"></div>
<div id="orders_chart1" style="width:560px; height:300px;"></div>
</td>
</tr>
</table>
<%= render 'nav', product: @product %>

<script type="text/javascript" charset="utf-8">
  $(function () {
    new Highcharts.Chart({
     	chart: { renderTo: 'orders_chart' },
		  title: { text: 'Orders by week' },
		  xAxis: { 
		  	type: 'datetime',
				maxZoom: 14 * 24 * 3600000,
		  	text: "Week Number",
		  	min: Date.UTC(<%= d2.first.year %>,<%= d2.first.month-1 %>,<%= d2.first.day %>),
		  	max: Date.UTC(<%= (d2.last+leadTime).year %>,<%= (d2.last+leadTime).month-1 %>,<%= (d2.last+leadTime).day %>),
		  },
		  yAxis: {
		  	min: 0,
		    title: { text: 'Orders'}
		  },
		  series: [{
				name: 'Weekly Sales',
		    data: [ <% (0..(d2.length-1)).each do |n| %>
		    	[Date.UTC(<%= d2[n].year %>, <%= d2[n].month-1 %>, <%= d2[n].day %>), <%= y[n] %> ]<%= "," if n != (d2.length-1) %>
		    <% end %>
		    ]
		  },{
				type: 'line',
				name: 'Regression Line',
				data: [
					[Date.UTC(<%= d2.first.year %>, <%= d2.first.month-1 %>, <%= d2.first.day %>),<%= startY %>],
					[Date.UTC(<%= d2.last.year %>, <%= d2.last.month-1 %>, <%= d2.last.day %>),<%= endY %>]
				],
				marker: {
					enabled: false
				},
				states: {
					hover: {
						lineWidth: 0
					}
				},
				enableMouseTracking: false
			},{
				type: 'line',
				name: 'Plus Sigma',
				data: [
					[Date.UTC(<%= d2.first.year %>, <%= d2.first.month-1 %>, <%= d2.first.day %>),<%= startY+sigma %>],
					[Date.UTC(<%= (d2.last+leadTime).year %>, <%= (d2.last+leadTime).month-1 %>, <%= (d2.last+leadTime).day %>),<%= prediction_y.last+sigma %>]
				],
				marker: {
					enabled: false
				},
				states: {
					hover: {
						lineWidth: 0
					}
				},
				enableMouseTracking: false,
				dashStyle: 'Dash'
			},{
				type: 'line',
				name: 'Minus Sigma',
				data: [
					[Date.UTC(<%= d2.first.year %>, <%= d2.first.month-1 %>, <%= d2.first.day %>),<%= startY-sigma %>],
					[Date.UTC(<%= (d2.last+leadTime).year %>, <%= (d2.last+leadTime).month-1 %>, <%= (d2.last+leadTime).day %>),<%= prediction_y.last-sigma %>]
				],
				marker: {
					enabled: false
				},
				states: {
					hover: {
						lineWidth: 0
					}
				},
				enableMouseTracking: false,
				dashStyle: 'Dash'
			},{
				type: 'line',
				name: 'Prediction Line',
				data: [
					[Date.UTC(<%= d2.last.year %>, <%= d2.last.month-1 %>, <%= d2.last.day %>),<%= prediction_y.first %>],
					[Date.UTC(<%= (d2.last+leadTime).year %>, <%= (d2.last+leadTime).month-1 %>, <%= (d2.last+leadTime).day %>),<%= prediction_y.last %>]
					],
				marker: {
					enabled: false
				},
				dashStyle: 'Dash'
			}]
    });
  });
</script>
<% lead60=Date.today+60 %>
<% lead90=Date.today+90 %>
<% lead120=Date.today+120 %>
<% start_prediction=Date.today %>
<script type="text/javascript" charset="utf-8">
  $(function () {
    new Highcharts.Chart({
     	chart: { renderTo: 'orders_chart1' },
		  title: { text: 'Inventory and Supplier Orders' },
		  xAxis: { 
		  	type: 'datetime',
				maxZoom: 14 * 24 * 3600000,
		  	text: "Week Number",
				plotBands: [{ 
					from: Date.UTC(<%= lead60.year %>, <%= lead60.month-1 %>, <%= lead60.day %>),
					to: Date.UTC(<%= lead60.year %>, <%= lead60.month-1 %>, <%= lead60.day+1 %>),
					color: 'rgba(0, 0, 0, .2)'
				},{ 
					from: Date.UTC(<%= lead90.year %>, <%= lead90.month-1 %>, <%= lead90.day %>),
					to: Date.UTC(<%= lead90.year %>, <%= lead90.month-1 %>, <%= lead90.day+1 %>),
					color: 'rgba(0, 0, 0, .2)'
				},{ 
					from: Date.UTC(<%= lead120.year %>, <%= lead120.month-1 %>, <%= lead120.day %>),
					to: Date.UTC(<%= lead120.year %>, <%= lead120.month-1 %>, <%= lead120.day+1 %>),
					color: 'rgba(0, 0, 0, .2)'
				}]
		  },
		  yAxis: {
		    title: { text: 'Inventory'}
		  },
		  series: [{
				name: 'Supplier Orders',
				type: 'column',
				data: [
					<% @product.product_orders.sort_by(&:date).each do |po| %>
						<% if po.product_counts.find_by_product_id(@product).is_box %>
							[Date.UTC(<%= po.date.year %>, <%= po.date.month-1 %>, <%= po.date.day %>),<%= po.product_counts.find_by_product_id(@product).count*@product.per_box %>]<%= "," if po != @product.product_orders.sort_by(&:date).last %>
						<% else %>
							[Date.UTC(<%= po.date.year %>, <%= po.date.month-1 %>, <%= po.date.day %>),<%= po.product_counts.find_by_product_id(@product).count %>]<%= "," if po != @product.product_orders.sort_by(&:date).last %>
						<% end %>
						
					<% end %>
				]
		  },{
				name: 'Inventory',
				data: [
					<% @product.inventory.sort_by(&:date).each do |inv| %>
						<% if inv.product_counts.find_by_product_id(@product).is_box %>
							[Date.UTC(<%= inv.date.year %>, <%= inv.date.month-1 %>, <%= inv.date.day %>),<%= inv.product_counts.find_by_product_id(@product).count*@product.per_box %>]<%= "," if inv != @product.inventory.sort_by(&:date).last %>
						<% else %>
							[Date.UTC(<%= inv.date.year %>, <%= inv.date.month-1 %>, <%= inv.date.day %>),<%= inv.product_counts.find_by_product_id(@product).count %>]<%= "," if inv != @product.inventory.sort_by(&:date).last %>
						<% end %>
					<% end %>
				]
		  },{
		  	type: 'line',
		  	name: 'Predicted Inventory Line',
		  	pointInterval: 24 * 3600 * 1000,
		  	pointStart: Date.UTC(<%= start_prediction.year %>,<%= start_prediction.month-1 %>,<%= start_prediction.day+1 %>),
		  	data: <%= @product.forcast_demand.map { |a| a.round(2) } %>,
		  	marker: {
					enabled: false
				},
				dashStyle: 'Dash'
			}]
    });
  });
</script>
<% end %>
<script>
$(function() {
	$("#accordion").accordion({ active: false, collapsible: true, heightStyle: "content"});
	$("#accordion1").accordion({ active: false, collapsible: true, heightStyle: "content"});
});
</script>